#!/bin/sh

HERE=$(dirname $(readlink -f ${0}))

LOGS=${HERE}/../logs
BINS=${HERE}/../output
OBJS=${HERE}/../build

CSUF=cross
NSUF=native

KALE="${PATH}"

mkdir -p ${LOGS} ${BINS}

# CROSS BUILD
[ -d ${BINS}/${1}-${CSUF} ] || make install \
    TARGET=${1} OUTPUT=${BINS}/${1}-${CSUF} \
    -j$(nproc) 2>&1 | tee ${LOGS}/${1}-${CSUF}.log

# CROSS PACKAGE
[ -h ${BINS}/${1}-${CSUF}/usr ] || (cd ${BINS}/${1}-${CSUF} && ln -s . usr)
[ -e ${BINS}/${1}-${CSUF}.tgz ] || (cd ${BINS} && tar pczf ${1}-${CSUF}.tgz ${1}-${CSUF})

# CROSS CLEANUP
rm -fr ${OBJS}/local/${1}

# DIRECTORY CLEANUP
rm -fr ${BINS}/${1}-${CSUF};
